### PR TITLE
Implemented Login and Authentication Reducer

### LINKED ISSUE #55: [React] Implement Login and Register screens with auth redux reducer
**Is your feature request related to a problem? Please describe.**
Login and Register screens are currently incomplete. Plan is to complete them along with continuing redux implementation with an authentication reducer.

### PR DESCRIPTION
**Pull request by amlannandy**
**List of changes -**

1. Completed Login Screen
2. Added a redux reducer for authentication
3. Created a reusable form input reducer
4. Added CORS package to flask server so that the React App can connect to it
5. Fixed login route in flask server which sent 406 status code instead of 200

**Demo**

screen-capture (1)

closes #55

### CODE REVIEW

**Comment by amlannandy** [comment]
@shivanshu1333 Hello. Could you please review this?

**Comment by amlannandy** [comment]
@shivanshu1333 Hey! Wanted to know if this PR will be merged? As I was assigned the issue.

**Comment by shivanshuraj1333** [comment]
@amlannandy can you please align the remember me checkbox with "Remember me"

**Comment by amlannandy** [comment]
@shivanshu1333 Fixed it.

**Review by shivanshuraj1333 — APPROVED** [review]

**Pull request merged**
