### PR TITLE
Data visualization between two cases

### LINKED ISSUE #219: Data visualization between two cases
**Is your feature request related to a problem? Please describe.**
Create some APIs to do analysis between two cases if required.
Presentation of observed analytics between two cases using graphs and tables.

### LINKED ISSUE #222: Bug in extraction of call logs and message
**Describe the bug**
Right now call logs data not appearing in phone_calllogs.tsv and sms.tsv
Update the scripts and create the table accordingly.

### PR DESCRIPTION
**Pull request by swapnalshahil**
# Description

Create some APIs to do analysis between two cases if required.
Presentation of observed analytics between two cases using graphs and tables.

Fixes #219 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://user-images.githubusercontent.com/58564017/128397987-31a78878-abd8-4f84-bcd4-a187b2b6ca75.mp4

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by swapnalshahil** [comment]
1. http://127.0.0.1:5000/commonreport/calls

    This API is responsible for getting common
    contact details between two cases.

    method = ['POST']
    {
        "case_one": "case1",
        "case_two": "case2"
    }

    2. http://127.0.0.1:5000/commonreport/coordinates

    This API is responsible for getting common
    location details between two cases.
    
    method = ['POST']
    {
        "case_one": "case1",
        "case_two": "case2"
    }

**Comment by swapnalshahil** [comment]
3. http://127.0.0.1:5000/commonreport/browser

    This API is responsible for fetching common browser
    searched history details between two cases.
    
    method = ['POST']
    {
        "case_one": "case1",
        "case_two": "case2"
    }
    4. http://127.0.0.1:5000/commonreport/sms

    This API is responsible for fetching common message
    details between two cases.

    method = ['POST']
    {
        "case_one": "case1",
        "case_two": "case2"
    }

**Comment by swapnalshahil** [comment]
@shivanshu1333  sir! Please review!🙂

**Comment by shivanshuraj1333** [comment]
Demo looks good, looking at the implementation right now, will review it by EOD

**Comment by swapnalshahil** [comment]
Landing page for analytics.

**Comment by swapnalshahil** [comment]
Now everything is up to date! 😅

**Review by shivanshuraj1333 — APPROVED** [review]
lgtm

**Pull request merged**
