### PR TITLE
Login user

### PR DESCRIPTION
**Pull request by MehtaManan07**
Also

> Implemented login and register user redux actions and reducer.
>  The alert component was not working, it was not showing any alert and therefore installed react-toastify and used it for showing alerts.
> Also the login route was returning 406 status code instead of 200 from the backend, corrected it as well!
#55

### CODE REVIEW

**Comment by amlannandy** [comment]
@MehtaManan07 I think you should have pinged on the issue thread once for confirmation before starting work on this, as you can see I was supposed to work on this and have also raised a PR for the same. I wouldn't have worked on this if I knew someone else was.

**Comment by MehtaManan07** [comment]
@amlannandy I Apologize for the communication gap. I had informed the maintainer way back on gitter but forgot to comment on the issue. I suggest you could follow gitter chats too to avoid further miscommunications like this.

**Comment by amlannandy** [comment]
> @amlannandy I Apologize for the communication gap. I had informed the maintainer way back on gitter but forgot to comment on the issue. I suggest you could follow gitter chats too to avoid further miscommunications like this.

I do check the gitter channel. You said you'd work on it around 10-12 days back but didn't open any issue/PR, which is why I opened #55  a couple of days ago and worked on it after approval from @shivanshu1333 this morning.

**Comment by shivanshuraj1333** [comment]
@MehtaManan07 that's why I told you earlier to create an issue and then continue with the work, it helps in maintaining visibility across the project and organization. It is not possible for any developer to keep track of gitter msgs, and hence opening an issue and assigning it to yourself is the suggested and accepted practice.
Also, please provide a proper name to PR and an appropriate description, with the required demo gif/screenshots, you can see the previous PRs created by me for reference.
Please attach a demo gif, resolve conflicts and keep these things in mind :)

**Pull request closed without merging**
