### PR TITLE
Added frontend support for OpenMF using React

### PR DESCRIPTION
**Pull request by shivanshuraj1333**
>     React based frontend is designed and implemented from scratch. 

**This pull request is addressed to solve issue #38 which is a subpart of issue #37** 

In this pull request, a complete frontend is designed, finishing the work related to Phase 1 of GSoC 2020 ([link to proposal](https://storage.googleapis.com/summerofcode-prod.appspot.com/gsoc/core_project/doc/6319729033084928_1585672193_OpenMF_shivanshu1333.pdf?Expires=1593447709&GoogleAccessId=summerofcode-prod%40appspot.gserviceaccount.com&Signature=W%2F%2BZzjzei7Cc2rxzawj7bvJnpGCBGWBnt2oxVLUjJH04xAguTZ%2FyhRBPf11ONp%2BAhx8iwecekkB5K1OBNimWM5pf%2BdyDUQAxcXQnFtGPPpyd91rcQfkTkwW6C9JKgQzPfc0ZMa0DvdtruEw2NS2OEELjF6DVJvTOaewwLhVpyxmnvmX1JxWJNCALza8%2FUyvGrsl4Sy7PSp9%2BqSosy3ksCbY5BUloDjVZoKmkwHpqn3J0rnHxtzPhK1mmmZ8C8vWzmQhmNFaz18u2MdIZBH2uKincZpcekVWwovQnzH3ci4MeDD6OHnh1jFZDlhdfTLNzvzpmtQccBQ0iCpw4L7IGLw%3D%3D))
Different tasks which are completed during this period are given below :-

1. Setting up tools for frontend development
2. Creating a React boilerplate with additional dependencies
3. Implementing Login and Admin panel designs in React, following Material UI
4. Implementing Manager and Extractor panel components in React
5. After the creation of components, components are connected to each other with React Router

### CODE REVIEW

**Comment by Wolf-Legend** [comment]
I did the test run, and it works like a charm :+1: 
I'd like to add some more points in addition to what we've discussed over video call :-
- try to use minimum colours i.e. make all your components monotonous following same colour scheme.
- add some more space in between Admin/user-management cards and everywhere else where you're using similar components.
- add gif of working demo of different pages (this will help in understanding the UI for anyone who wants to contribute)
- add a separate Readme for React-fronted and explain how to setup it locally

Change the other components as discussed over video call and commit before the 1st phase evaluation ends.
Also, feel free to contact any of the mentor if required.

**Comment by shivanshuraj1333** [comment]
**This is the gif of the home page, please let me know if this works as a demo for this page.**

I'm working on the suggestions and will squash all the modifications in a single commit along with a Readme file. I'll add the demo of other pages if you like this.


<p align="center">

</p>

**<p align="center">Home page of OpenMF</p>**

**Comment by vivonk** [comment]
Work looks good. @shivanshu1333 can you add screenshots of all the pages which you have designed and implemented so far in comments?
It becomes easy to see output of work and then review code.

**Comment by shivanshuraj1333** [comment]
Yes, @vivonk given below are the other pages, please note that the different components like existing cases etc will be loaded once the development of the flask backend is complete and the database is also setup.

<p align="center">

</p>

**<p align="center">Admin page of OpenMF</p>**

<p align="center">

</p>

**<p align="center">Manager page of OpenMF</p>**

<p align="center">

</p>

**<p align="center">Exttractor page of OpenMF</p>**

**Review by Wolf-Legend — APPROVED** [review]
Approved, looks good to me. Yes, as discussed in the video call, render all the remaining components dynamically once the database is connected, also remember to use pagination (you forgot to include this in the demo you showed to me).
@shivanshu1333 Include a separate Readme.md for frontend similar to what you've done in the backend in the PR #41

**Review by vivonk — APPROVED** [review]
LGTG

**Pull request merged**
