### PR TITLE
Login and Add user with Google

### LINKED ISSUE #283: [Backend]Management and Extractor with Google Auth
Google Login _ONLY_ for Admin
---

So far only the Admins can log in with Google, not the _Extractor_ or _Management_.
All users should be allowed to be logged in with  Google.

### PR DESCRIPTION
**Pull request by PrerakMathur20**
# Description

* Added functionality for an admin to add a user with Google. 
* Earlier login with google was restricted to admins only. Now all users can login with google.

Fixes #283 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Login and registration for Admin works
- [x] Login and registration for Management works
- [x] Login and registration for Extractor works

Also, include screenshots for the verification and reviewing purpose.

* If no Role is selected
Screenshot 2022-07-09 at 8 22 19 AM

* For Management
Screenshot 2022-07-09 at 8 22 40 AM

* For Extractor
Screenshot 2022-07-09 at 8 22 31 AM

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation **(N/A)**
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works **(N/A)**
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules **(N/A)**

### CODE REVIEW

**Comment by shivanshuraj1333** [comment]
Can you also add a small demo?
Thanks!

**Comment by swapnalshahil** [comment]
/lgtm
merge hold for demo

**Comment by PrerakMathur20** [comment]
@shivanshu1333 @swapnalshahil 

Demo
---
Sure. Here's a demo for the same. Let me know if anything else is required.

This demo shows, how an Admin (Logged In by Google), can Add new members of Extractor as well as Management, via Google with the same email Id for all 3. And Obviously the same works for different emails as well.

https://user-images.githubusercontent.com/76054330/180640695-38411a66-c34e-48e1-a666-56bcabd836c7.mp4

**Review by swapnalshahil — APPROVED** [review]
LGTM

**Pull request merged**
