### PR TITLE
Design and implemented Database Model and added more APIs

### PR DESCRIPTION
**Pull request by shivanshuraj1333**
>     Added more Flask RESTful APIs and designed and implemented the Database model from scratch. 

**This pull request is addressed to solve issue #42   which is a subpart of issue #37**

In this pull request, a complete database model is designed and added more APIs.
Different tasks which are completed during this period are given below:-

1. Setting up SQLite3, flask_sqlalchemy and other tools for database model development
2. Writing down APIs details, metadata, in Flask with additional dependencies
3. Setting up MySQL data models and init SQL scripts
4. Implementing the required case related APIs.

### CODE REVIEW

**Comment by shivanshuraj1333** [comment]
>     Below is the modified data hierarchy which a user can browse from react frontend to see the relevant files of any session:
<p align="center">

</p>
<p align="center">Data hierarchy designed to incorporate extraction and retrieval of data from Flask Rest APIs used to show data on frontend based on React</p>

<p align="center">

</p>
<p align="center">Every case consists of db, report, tsv and json folder depending on the parameters provided during extraction</p>

**Review by Wolf-Legend — APPROVED** [review]
I can see all the requested changes and modifications.
LGTM, approved!

**Review by vivonk — APPROVED** [review]
Good Job @shivanshu1333

**Comment by vivonk** [comment]
@shivanshu1333 @charithccmc @Wolf-Legend now codebase is growing so should we start focusing on component testing and build testing?

**Comment by shivanshuraj1333** [comment]
Yes @vivonk we should, moreover, I have some other improvements in my mind, will soon make issues and add **Hactoberfest** tag with them as Hacoberfest will start soon, it will help developers to find relevant issues.

**Pull request merged**
