### PR TITLE
Update Sidebar.js

### LINKED ISSUE #254: Side Nav Buttons are non-functional
**Describe the bug**
The **Home, Contact, About** options in the side nav are non-functional.

**To Reproduce**
1. Go to `localhost:3000`
2. Login
3. Click on the Home, Contact, About button

**Expected behavior**
Those buttons should redirect the user to their respective pages.

**Screenshots**
Screenshot 2022-02-27 at 11 42 46 PM

**Desktop (please complete the following information):**
 - OS: [MacOs]
 - Browser [Any]
 - Version [MacOS 11.6]

**Additional context**

### PR DESCRIPTION
**Pull request by PrerakMathur20**
# Description

The **Home, Contact** and **About** buttons in the Sidenav weren't functioning properly as they were not linked to their respective pages.
The required changes were made and the following files were updated with the necessary changes:

* `React-frontend/src/components/Sidebar.js`
* `React-frontend/src/components/Extractor/Sidebar.js`
* `React-frontend/src/components/Management/Sidebar.js`

Fixes #254 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] All pages are working as they were, without any issues.
- [x] Linking has been done in sync with the pages and links in `App.js`

Also, include screenshots for the verification and reviewing purpose.
**Not relevant**

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have made corresponding changes to the documentation **(N/A)**
- [ ] I have added tests that prove my fix is effective or that my feature works **(N/A)**
- [ ] New and existing unit tests pass locally with my changes **(N/A)**
- [ ] Any dependent changes have been merged and published in downstream modules **(N/A)**

### CODE REVIEW

**Comment by swapnalshahil** [comment]
@PrerakMathur20 Did you test if it works when you log in with extractor or management role? I don't think this will work for them also!

**Comment by PrerakMathur20** [comment]
> @PrerakMathur20 Did you test if it works when you log in with extractor or management role? I don't think this will work for them also!

Yes, you're right, this fix isn't working for the extractor or management role. My bad. But don't worry I've figured out the issue and am currently working on fixing it. I'll update this PR soon.

**Comment by PrerakMathur20** [comment]
I've made the required changes and now the **Home, Contact** and **About**, links on the Sidebar are now redirecting to their respective pages now for all **Admin, Extractor** and **Management** users.

Kindly review these changes and let me know if I've missed out anything 😄

**Review by swapnalshahil — CHANGES_REQUESTED** [review]
@PrerakMathur20 I think you should not commit `.DS_Store`. You can ignore this. It might be not visible on Mac, so you can put this in .gitignore.

**Comment by PrerakMathur20** [comment]
My apologies. I have removed the `.DS_Store` file as well as included it in the `.gitignore` file.

**Review by swapnalshahil — APPROVED** [review]
Looks good to me!

**Pull request merged**
