### PR TITLE
Redux setup and created alerts reducer

### PR DESCRIPTION
**Pull request by amlannandy**
**Description**

Initialized redux in project and set up a reducer for displaying alerts.

**Screenshot**

alert

**Testing**

To create an alert

```
import { setAlert } from '../store/actions/alerts';
import { useDispatch } from 'react-redux';

const dispatch = useDispatch();
dispatch(setAlert('This is a Test Alert', 'danger', 2000));
```

closes #52

### CODE REVIEW

**Review by shivanshuraj1333 — DISMISSED** [review]
LGTM

**Comment by amlannandy** [comment]
@shivanshu1333 Thanks!
@charithccmc @Wolf-Legend Hello. Could you please also review it? As when it gets merged, I can start with adding a reducer for authentication.

**Comment by shivanshuraj1333** [comment]
@amlannandy Resolve conflicts.

**Comment by amlannandy** [comment]
> @amlannandy Resolve conflicts.

@shivanshu1333 Done 👍🏻

**Review by MehtaManan07 — APPROVED** [review]
Looks fine to me.

**Review by shivanshuraj1333 — APPROVED** [review]
LGTM

**Pull request merged**
