### PR TITLE
Implementation of some analytics api on front end OpenMF

### LINKED ISSUE #206: [Frontend]: Implementation on analytics section in management.
**Is your feature request related to a problem? Please describe.**

Adding features on frontend OpenMF analytics section in management: 

Implementation of #193 Keyword search (for getting cases)
Implementation of #194 Keyword search from cases
Implementation of #198 Maximum common word/data between two cases
Implementation of #199 List all common word/data between two cases
Implementation of #205 Create Filter API to get Cases by Date or range of date.

### LINKED ISSUE #211: Tag association
**Is your feature request related to a problem? Please describe.**

Tag association and tag-based search like searching cases that are tagged with theft to get all the theft-related cases.

### LINKED ISSUE #212: Customized Keyword search
**Is your feature request related to a problem? Please describe.**
Customized keyword search
Example -  `<kw1> + <kw2> + … + <kwN>`

### LINKED ISSUE #214: Report.txt did not get store when extracting from POSTMAN
**Describe the bug**

Report.txt did not get store when extracting from POSTMAN
When extracting from CMD report.txt gets stored in Report dir. But from POSTMAN it didn't.

**Expected behavior**
It should store report.txt even when extracting from POSTMAN.

### PR DESCRIPTION
**Pull request by swapnalshahil**
# Description

Adding features on frontend OpenMF analytics section in management:

Implementation of #193 Keyword search (for getting cases)
Implementation of #194 Keyword search from cases
Implementation of #198 Maximum common word/data between two cases
Implementation of #199 List all common word/data between two cases
Implementation of #205 Create Filter API to get Cases by Date or range of date.

Fixes #206 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Also, include screenshots for the verification and reviewing purpose.

https://user-images.githubusercontent.com/58564017/126034517-1ada3eb6-962f-4b64-90f9-b2797924794c.mp4

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by swapnalshahil** [comment]
@shivanshu1333 sir! Have a look please. 😅

**Comment by swapnalshahil** [comment]
Right now Analytics Page is blank which will be the common page for analytics. It will show all information about OpenMF analytics. I will make this page after implementing all analytics work.

**Comment by swapnalshahil** [comment]
Week 7 from here 🙄

**Comment by swapnalshahil** [comment]
# Description

Adding features on frontend OpenMF analytics section in management:
Tag association and tag-based search like searching cases that are tagged with theft to get all the theft-related cases.


Fixes #214 #211 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update


Also, include screenshots for the verification and reviewing purpose.


https://user-images.githubusercontent.com/58564017/126624422-f0b70990-45a8-4543-8acf-9e14eb2a48d2.mp4






# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

**Comment by swapnalshahil** [comment]
1. API: http://127.0.0.1:5000/keyword/search/tags

Method = ["POST"]

This API will search for cases that have particular tags assigned.

{
    "tags": "tag1,tag2"
}



2. API: http://127.0.0.1:5000/keyword/custom/search

Method = ["POST"]

This API will find cases that have all keywords in them.

{
    "keyword": "keyword1,keyword2,keyword3"
}

**Comment by swapnalshahil** [comment]
# Description

Adding features on frontend OpenMF analytics section in management:
Customized keyword search
Example - `<kw1> + <kw2> + … + <kwN>`

Fixes #212  

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update


Also, include screenshots for the verification and reviewing purpose.

https://user-images.githubusercontent.com/58564017/126745288-fd4a5f4f-10fa-4c71-a5d7-d4af240c0b5c.mp4






# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

**Review by shivanshuraj1333 — APPROVED** [review]
merging

**Pull request merged**
